### ISSUE TITLE
unresolved imports `winping::Buffer`, `winping::Pinger`

### ISSUE THREAD

**Issue by dulinux** [TyPR124/winping#1]
Hello, trying the super basic ping example gives an unresolved import. No Buffer ou Pinger in the root.

```
duli@uvm:~/projects/rust/ptest$ cat Cargo.toml
[package]
name = "ptest"
version = "0.1.0"
authors = ["dulinux <someemail@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winping = "0.9.1"

duli@uvm:~/projects/rust/ptest$ cargo build
    Updating crates.io index
   Compiling winapi_forked_icmpapi v0.3.7
   Compiling static_assertions v1.1.0
   Compiling lazy_static v1.4.0
   Compiling winping v0.9.1
   Compiling ptest v0.1.0 (/mnt/homes/duli/projects/rust/ptest)
error[E0432]: unresolved imports `winping::Buffer`, `winping::Pinger`
 --> src/main.rs:2:15
  |
2 | use winping::{Buffer, Pinger};
  |               ^^^^^^  ^^^^^^ no `Pinger` in the root
  |               |
  |               no `Buffer` in the root

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `ptest`.

To learn more, run the command again with --verbose.
```

Any pointers?

Thanks a lot!

**Comment by TyPR124** [comment]
I can reproduce this when building for Linux. This crate only runs on Windows, so it would be useless to include it in a Linux-targeted build.

If you are trying to use this as a Windows-specific piece of a cross-platform project, you can try to use it as a Windows-specific dependency with:

```
[target.'cfg(windows)'.dependencies]
winping = "0.9.1"
```

but if that doesn't work for any reason let me know.

If you are targeting Windows but still getting this (or any other) error, let me know.

**Comment by dulinux** [comment]
> 
> 
> I can reproduce this when building for Linux. This crate only runs on Windows, so it would be useless to include it in a Linux-targeted build.

Oh, sorry. I was hoping to use in a Linux application. I guess you can close the issue.

Thanks a lot.
