### ISSUE TITLE
Please implement std::error::Error trait

### ISSUE THREAD

**Issue by denisbrodbeck** [TyPR124/winping#2]
Hello @TyPR124,
thanks for this rust library - works great in my windows app.

One particular issue popped up during development:

I tried to wrap `winping::Error` in my own Error type (kind of like in [this example](https://doc.rust-lang.org/stable/rust-by-example/error/multiple_error_types/wrap_error.html)), but fail to cast your error type to `dyn std::error:Error` (error message `the trait bound 'winping::error::Error: std::error::Error' is not satisfied. required for the cast to the object type 'dyn std::error::Error'`).

I think my issue might be the missing implementation of the `std::error::Error` trait in `winping::Error`.

I get my code compiling by adding a single `impl std::error::Error for Error {}` to your [src/error.rs](https://github.com/TyPR124/winping/blob/da46035c00af73b9f6110ec9d84a4fee62a81702/src/error.rs#L112).

```rust
...
...
impl Display for Error {
    fn fmt(&self, out: &mut Formatter) -> fmt::Result {
        Debug::fmt(self, out)
    }
}

impl std::error::Error for Error {}
```

What do you think?

**Comment by TyPR124** [comment]
Thank you for the report! `winping::Error` should definitely be implementing the Error trait. Do you mind opening a pull request with that change? I don't believe this would be a breaking change, so I can get it merged and released pretty quickly.

**Comment by TyPR124** [comment]
I actually went ahead and made the change myself, as I noticed another error type (`winping::CreateError`) was missing similar impls. Both error types now implement `std::error::Error` in version 0.9.3 (I created and subsequently yanked 0.9.2 because a dependency [quote 1.0.2] had been yanked, so 0.9.3 includes updated dependencies).

**Comment by denisbrodbeck** [comment]
This is great. Thank you 👍
